# Generated by Django 5.2.7 on 2025-12-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proveedores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedor",
            name="prv_rut",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
