# Generated by Django 5.2.8 on 2025-11-15 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("archivos", "0001_initial"),
        ("cursos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivocurso",
            name="cus_id",
            field=models.ForeignKey(
                db_column="cus_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="cursos.cursoseccion",
            ),
        ),
        migrations.AddField(
            model_name="archivopersona",
            name="arc_id",
            field=models.ForeignKey(
                db_column="arc_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="archivos.archivo",
            ),
        ),
        migrations.AddField(
            model_name="archivopersona",
            name="cus_id",
            field=models.ForeignKey(
                db_column="cus_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="cursos.cursoseccion",
            ),
        ),
    ]
