# Generated by Django 5.2.8 on 2025-11-15 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("archivos", "0002_initial"),
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivopersona",
            name="per_id",
            field=models.ForeignKey(
                db_column="per_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="personas.persona",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="archivocurso",
            unique_together={("arc_id", "cus_id")},
        ),
        migrations.AlterUniqueTogether(
            name="archivopersona",
            unique_together={("arc_id", "per_id", "cus_id")},
        ),
    ]
