# Generated by Django 5.2.7 on 2025-10-19 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("maestros", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                ("per_id", models.AutoField(primary_key=True, serialize=False)),
                ("per_fecha_hora", models.DateTimeField()),
                ("per_run", models.IntegerField()),
                ("per_dv", models.CharField(max_length=1)),
                ("per_apelpat", models.CharField(max_length=50)),
                ("per_apelmat", models.CharField(blank=True, max_length=50, null=True)),
                ("per_nombres", models.CharField(max_length=50)),
                ("per_email", models.EmailField(max_length=100)),
                ("per_fecha_nac", models.DateTimeField()),
                ("per_direccion", models.CharField(max_length=255)),
                ("per_tipo_fono", models.IntegerField()),
                ("per_fono", models.CharField(max_length=15)),
                ("per_alergia_enfermedad", models.TextField(blank=True, null=True)),
                ("per_limitacion", models.TextField(blank=True, null=True)),
                (
                    "per_nom_emergencia",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "per_fono_emergencia",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("per_otros", models.TextField(blank=True, null=True)),
                ("per_num_mmaa", models.IntegerField(blank=True, null=True)),
                (
                    "per_profesion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "per_tiempo_nnaj",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "per_tiempo_adulto",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "per_religion",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("per_apodo", models.CharField(max_length=50)),
                ("per_foto", models.TextField(blank=True, null=True)),
                ("per_vigente", models.BooleanField()),
                (
                    "com_id",
                    models.ForeignKey(
                        db_column="com_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maestros.comuna",
                    ),
                ),
                (
                    "esc_id",
                    models.ForeignKey(
                        db_column="esc_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maestros.estadocivil",
                    ),
                ),
                (
                    "usu_id",
                    models.ForeignKey(
                        db_column="usu_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Persona",
                "verbose_name_plural": "Personas",
                "db_table": "persona",
            },
        ),
        migrations.CreateModel(
            name="PersonaFormador",
            fields=[
                ("pef_id", models.AutoField(primary_key=True, serialize=False)),
                ("pef_hab_1", models.BooleanField()),
                ("pef_hab_2", models.BooleanField()),
                ("pef_verif", models.BooleanField()),
                ("pef_historial", models.TextField(blank=True, null=True)),
                (
                    "per_id",
                    models.ForeignKey(
                        db_column="per_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personas.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Persona Formador",
                "verbose_name_plural": "Personas Formadores",
                "db_table": "persona_formador",
            },
        ),
        migrations.CreateModel(
            name="PersonaIndividual",
            fields=[
                ("pei_id", models.AutoField(primary_key=True, serialize=False)),
                ("pei_vigente", models.BooleanField()),
                (
                    "car_id",
                    models.ForeignKey(
                        db_column="car_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maestros.cargo",
                    ),
                ),
                (
                    "dis_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="dis_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maestros.distrito",
                    ),
                ),
                (
                    "per_id",
                    models.ForeignKey(
                        db_column="per_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personas.persona",
                    ),
                ),
                (
                    "zon_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="zon_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maestros.zona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Persona Individual",
                "verbose_name_plural": "Personas Individuales",
                "db_table": "persona_individual",
            },
        ),
        migrations.CreateModel(
            name="PersonaVehiculo",
            fields=[
                ("pev_id", models.AutoField(primary_key=True, serialize=False)),
                ("pev_marca", models.CharField(max_length=50)),
                ("pev_modelo", models.CharField(max_length=50)),
                ("pev_patente", models.CharField(max_length=10)),
                (
                    "per_id",
                    models.ForeignKey(
                        db_column="per_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personas.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehículo de Persona",
                "verbose_name_plural": "Vehículos de Personas",
                "db_table": "persona_vehiculo",
            },
        ),
        migrations.CreateModel(
            name="PersonaGrupo",
            fields=[
                ("peg_id", models.AutoField(primary_key=True, serialize=False)),
                ("peg_vigente", models.BooleanField()),
                (
                    "gru_id",
                    models.ForeignKey(
                        db_column="gru_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maestros.grupo",
                    ),
                ),
                (
                    "per_id",
                    models.ForeignKey(
                        db_column="per_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personas.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Persona en Grupo",
                "verbose_name_plural": "Personas en Grupos",
                "db_table": "persona_grupo",
                "unique_together": {("gru_id", "per_id")},
            },
        ),
        migrations.CreateModel(
            name="PersonaNivel",
            fields=[
                ("pen_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "niv_id",
                    models.ForeignKey(
                        db_column="niv_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maestros.nivel",
                    ),
                ),
                (
                    "per_id",
                    models.ForeignKey(
                        db_column="per_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personas.persona",
                    ),
                ),
                (
                    "ram_id",
                    models.ForeignKey(
                        db_column="ram_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maestros.rama",
                    ),
                ),
            ],
            options={
                "verbose_name": "Persona Nivel",
                "verbose_name_plural": "Personas Niveles",
                "db_table": "persona_nivel",
                "unique_together": {("per_id", "niv_id", "ram_id")},
            },
        ),
    ]
