# Generated by Django 5.2.7 on 2025-12-03 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personacurso",
            name="per_id",
            field=models.ForeignKey(
                db_column="per_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personacurso",
                to="personas.persona",
            ),
        ),
    ]
