# Generated by Django 5.2.7 on 2025-10-19 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("maestros", "0001_initial"),
        ("personas", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                ("cur_id", models.AutoField(primary_key=True, serialize=False)),
                ("cur_fecha_hora", models.DateTimeField()),
                ("cur_fecha_solicitud", models.DateTimeField()),
                ("cur_codigo", models.CharField(max_length=10)),
                (
                    "cur_descripcion",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("cur_observacion", models.TextField(blank=True, null=True)),
                ("cur_administra", models.IntegerField()),
                (
                    "cur_cuota_con_almuerzo",
                    models.DecimalField(decimal_places=6, max_digits=21),
                ),
                (
                    "cur_cuota_sin_almuerzo",
                    models.DecimalField(decimal_places=6, max_digits=21),
                ),
                ("cur_modalidad", models.IntegerField()),
                ("cur_tipo_curso", models.IntegerField()),
                ("cur_lugar", models.CharField(blank=True, max_length=100, null=True)),
                ("cur_estado", models.IntegerField()),
                (
                    "car_id_responsable",
                    models.ForeignKey(
                        db_column="car_id_responsable",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maestros.cargo",
                    ),
                ),
                (
                    "com_id_lugar",
                    models.ForeignKey(
                        blank=True,
                        db_column="com_id_lugar",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maestros.comuna",
                    ),
                ),
                (
                    "per_id_responsable",
                    models.ForeignKey(
                        db_column="per_id_responsable",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personas.persona",
                    ),
                ),
                (
                    "tcu_id",
                    models.ForeignKey(
                        db_column="tcu_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maestros.tipocurso",
                    ),
                ),
                (
                    "usu_id",
                    models.ForeignKey(
                        db_column="usu_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
                "db_table": "curso",
            },
        ),
        migrations.CreateModel(
            name="CursoAlimentacion",
            fields=[
                ("cua_id", models.AutoField(primary_key=True, serialize=False)),
                ("cua_fecha", models.DateTimeField()),
                ("cua_tiempo", models.IntegerField()),
                ("cua_descripcion", models.CharField(max_length=100)),
                ("cua_cantidad_adicional", models.IntegerField()),
                ("cua_vigente", models.BooleanField()),
                (
                    "ali_id",
                    models.ForeignKey(
                        db_column="ali_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maestros.alimentacion",
                    ),
                ),
                (
                    "cur_id",
                    models.ForeignKey(
                        db_column="cur_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cursos.curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alimentación de Curso",
                "verbose_name_plural": "Alimentaciones de Curso",
                "db_table": "curso_alimentacion",
            },
        ),
        migrations.CreateModel(
            name="CursoCuota",
            fields=[
                ("cuu_id", models.AutoField(primary_key=True, serialize=False)),
                ("cuu_tipo", models.IntegerField()),
                ("cuu_fecha", models.DateTimeField()),
                ("cuu_valor", models.DecimalField(decimal_places=6, max_digits=21)),
                (
                    "cur_id",
                    models.ForeignKey(
                        db_column="cur_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cursos.curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuota de Curso",
                "verbose_name_plural": "Cuotas de Curso",
                "db_table": "curso_cuota",
            },
        ),
        migrations.CreateModel(
            name="CursoFecha",
            fields=[
                ("cuf_id", models.AutoField(primary_key=True, serialize=False)),
                ("cuf_fecha_inicio", models.DateTimeField()),
                ("cuf_fecha_termino", models.DateTimeField()),
                ("cuf_tipo", models.IntegerField()),
                (
                    "cur_id",
                    models.ForeignKey(
                        db_column="cur_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cursos.curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fecha de Curso",
                "verbose_name_plural": "Fechas de Curso",
                "db_table": "curso_fecha",
            },
        ),
        migrations.CreateModel(
            name="CursoSeccion",
            fields=[
                ("cus_id", models.AutoField(primary_key=True, serialize=False)),
                ("cus_seccion", models.IntegerField()),
                ("cus_cant_participante", models.IntegerField()),
                (
                    "cur_id",
                    models.ForeignKey(
                        db_column="cur_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cursos.curso",
                    ),
                ),
                (
                    "ram_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="ram_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maestros.rama",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sección de Curso",
                "verbose_name_plural": "Secciones de Curso",
                "db_table": "curso_seccion",
                "unique_together": {("cur_id", "cus_seccion")},
            },
        ),
        migrations.CreateModel(
            name="PersonaCurso",
            fields=[
                ("pec_id", models.AutoField(primary_key=True, serialize=False)),
                ("pec_observacion", models.TextField(blank=True, null=True)),
                ("pec_registro", models.BooleanField()),
                ("pec_acreditado", models.BooleanField()),
                (
                    "ali_id",
                    models.ForeignKey(
                        db_column="ali_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maestros.alimentacion",
                    ),
                ),
                (
                    "cus_id",
                    models.ForeignKey(
                        db_column="cus_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cursos.cursoseccion",
                    ),
                ),
                (
                    "niv_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="niv_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maestros.nivel",
                    ),
                ),
                (
                    "per_id",
                    models.ForeignKey(
                        db_column="per_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personas.persona",
                    ),
                ),
                (
                    "rol_id",
                    models.ForeignKey(
                        db_column="rol_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maestros.rol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscripción de Persona en Curso",
                "verbose_name_plural": "Inscripciones de Personas en Cursos",
                "db_table": "persona_curso",
                "unique_together": {("per_id", "cus_id")},
            },
        ),
        migrations.CreateModel(
            name="PersonaEstadoCurso",
            fields=[
                ("peu_id", models.AutoField(primary_key=True, serialize=False)),
                ("peu_fecha_hora", models.DateTimeField()),
                ("peu_estado", models.IntegerField()),
                ("peu_vigente", models.BooleanField()),
                (
                    "pec_id",
                    models.ForeignKey(
                        db_column="pec_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cursos.personacurso",
                    ),
                ),
                (
                    "usu_id",
                    models.ForeignKey(
                        db_column="usu_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado de Inscripción de Persona",
                "verbose_name_plural": "Estados de Inscripción de Personas",
                "db_table": "persona_estado_curso",
            },
        ),
        migrations.CreateModel(
            name="CursoCoordinador",
            fields=[
                ("cuc_id", models.AutoField(primary_key=True, serialize=False)),
                ("cuc_cargo", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "car_id",
                    models.ForeignKey(
                        db_column="car_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maestros.cargo",
                    ),
                ),
                (
                    "cur_id",
                    models.ForeignKey(
                        db_column="cur_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cursos.curso",
                    ),
                ),
                (
                    "per_id",
                    models.ForeignKey(
                        db_column="per_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personas.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coordinador de Curso",
                "verbose_name_plural": "Coordinadores de Curso",
                "db_table": "curso_coordinador",
                "unique_together": {("cur_id", "per_id")},
            },
        ),
        migrations.CreateModel(
            name="CursoFormador",
            fields=[
                ("cuo_id", models.AutoField(primary_key=True, serialize=False)),
                ("cuo_director", models.BooleanField()),
                (
                    "cur_id",
                    models.ForeignKey(
                        db_column="cur_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cursos.curso",
                    ),
                ),
                (
                    "per_id",
                    models.ForeignKey(
                        db_column="per_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personas.persona",
                    ),
                ),
                (
                    "rol_id",
                    models.ForeignKey(
                        db_column="rol_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maestros.rol",
                    ),
                ),
                (
                    "cus_id",
                    models.ForeignKey(
                        db_column="cus_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cursos.cursoseccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formador de Curso",
                "verbose_name_plural": "Formadores de Curso",
                "db_table": "curso_formador",
                "unique_together": {("cur_id", "per_id", "cus_id")},
            },
        ),
    ]
