# Generated by Django 5.2.7 on 2025-12-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cursos", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="cur_latitud",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="cur_longitud",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
