# Generated by Django 5.2.7 on 2025-10-19 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alimentacion",
            fields=[
                ("ali_id", models.AutoField(primary_key=True, serialize=False)),
                ("ali_descripcion", models.CharField(max_length=100)),
                ("ali_tipo", models.IntegerField()),
                ("ali_vigente", models.BooleanField()),
            ],
            options={
                "verbose_name": "Alimentación",
                "verbose_name_plural": "Alimentaciones",
                "db_table": "alimentacion",
            },
        ),
        migrations.CreateModel(
            name="Cargo",
            fields=[
                ("car_id", models.AutoField(primary_key=True, serialize=False)),
                ("car_descripcion", models.CharField(max_length=100)),
                ("car_vigente", models.BooleanField()),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
                "db_table": "cargo",
            },
        ),
        migrations.CreateModel(
            name="ConceptoContable",
            fields=[
                ("coc_id", models.AutoField(primary_key=True, serialize=False)),
                ("coc_descripcion", models.CharField(max_length=50)),
                ("coc_vigente", models.BooleanField()),
            ],
            options={
                "verbose_name": "Concepto Contable",
                "verbose_name_plural": "Conceptos Contables",
                "db_table": "concepto_contable",
            },
        ),
        migrations.CreateModel(
            name="Distrito",
            fields=[
                ("dis_id", models.AutoField(primary_key=True, serialize=False)),
                ("dis_descripcion", models.CharField(max_length=100)),
                ("dis_vigente", models.BooleanField()),
            ],
            options={
                "verbose_name": "Distrito",
                "verbose_name_plural": "Distritos",
                "db_table": "distrito",
            },
        ),
        migrations.CreateModel(
            name="EstadoCivil",
            fields=[
                ("esc_id", models.AutoField(primary_key=True, serialize=False)),
                ("esc_descripcion", models.CharField(max_length=50)),
                ("esc_vigente", models.BooleanField()),
            ],
            options={
                "verbose_name": "Estado Civil",
                "verbose_name_plural": "Estados Civiles",
                "db_table": "estado_civil",
            },
        ),
        migrations.CreateModel(
            name="Nivel",
            fields=[
                ("niv_id", models.AutoField(primary_key=True, serialize=False)),
                ("niv_descripcion", models.CharField(max_length=50)),
                ("niv_orden", models.IntegerField()),
                ("niv_vigente", models.BooleanField()),
            ],
            options={
                "verbose_name": "Nivel",
                "verbose_name_plural": "Niveles",
                "db_table": "nivel",
            },
        ),
        migrations.CreateModel(
            name="Provincia",
            fields=[
                ("pro_id", models.AutoField(primary_key=True, serialize=False)),
                ("pro_descripcion", models.CharField(max_length=100)),
                ("pro_vigente", models.BooleanField()),
            ],
            options={
                "verbose_name": "Provincia",
                "verbose_name_plural": "Provincias",
                "db_table": "provincia",
            },
        ),
        migrations.CreateModel(
            name="Rama",
            fields=[
                ("ram_id", models.AutoField(primary_key=True, serialize=False)),
                ("ram_descripcion", models.CharField(max_length=50)),
                ("ram_vigente", models.BooleanField()),
            ],
            options={
                "verbose_name": "Rama",
                "verbose_name_plural": "Ramas",
                "db_table": "rama",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("reg_id", models.AutoField(primary_key=True, serialize=False)),
                ("reg_descripcion", models.CharField(max_length=100)),
                ("reg_vigente", models.BooleanField()),
            ],
            options={
                "verbose_name": "Región",
                "verbose_name_plural": "Regiones",
                "db_table": "region",
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                ("rol_id", models.AutoField(primary_key=True, serialize=False)),
                ("rol_descripcion", models.CharField(max_length=50)),
                ("rol_tipo", models.IntegerField()),
                ("rol_vigente", models.BooleanField()),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "db_table": "rol",
            },
        ),
        migrations.CreateModel(
            name="TipoArchivo",
            fields=[
                ("tar_id", models.AutoField(primary_key=True, serialize=False)),
                ("tar_descripcion", models.CharField(max_length=50)),
                ("tar_vigente", models.BooleanField()),
            ],
            options={
                "verbose_name": "Tipo de Archivo",
                "verbose_name_plural": "Tipos de Archivo",
                "db_table": "tipo_archivo",
            },
        ),
        migrations.CreateModel(
            name="TipoCurso",
            fields=[
                ("tcu_id", models.AutoField(primary_key=True, serialize=False)),
                ("tcu_descripcion", models.CharField(max_length=100)),
                ("tcu_tipo", models.IntegerField()),
                ("tcu_cant_participante", models.IntegerField(blank=True, null=True)),
                ("tcu_vigente", models.BooleanField()),
            ],
            options={
                "verbose_name": "Tipo de Curso",
                "verbose_name_plural": "Tipos de Curso",
                "db_table": "tipo_curso",
            },
        ),
        migrations.CreateModel(
            name="Zona",
            fields=[
                ("zon_id", models.AutoField(primary_key=True, serialize=False)),
                ("zon_descripcion", models.CharField(max_length=100)),
                ("zon_unilateral", models.BooleanField()),
                ("zon_vigente", models.BooleanField()),
            ],
            options={
                "verbose_name": "Zona",
                "verbose_name_plural": "Zonas",
                "db_table": "zona",
            },
        ),
        migrations.CreateModel(
            name="Grupo",
            fields=[
                ("gru_id", models.AutoField(primary_key=True, serialize=False)),
                ("gru_descripcion", models.CharField(max_length=100)),
                ("gru_vigente", models.BooleanField()),
                (
                    "dis_id",
                    models.ForeignKey(
                        db_column="dis_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maestros.distrito",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo",
                "verbose_name_plural": "Grupos",
                "db_table": "grupo",
            },
        ),
        migrations.CreateModel(
            name="Comuna",
            fields=[
                ("com_id", models.AutoField(primary_key=True, serialize=False)),
                ("com_descripcion", models.CharField(max_length=100)),
                ("com_vigente", models.BooleanField()),
                (
                    "pro_id",
                    models.ForeignKey(
                        db_column="pro_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maestros.provincia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comuna",
                "verbose_name_plural": "Comunas",
                "db_table": "comuna",
            },
        ),
        migrations.AddField(
            model_name="provincia",
            name="reg_id",
            field=models.ForeignKey(
                db_column="reg_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="maestros.region",
            ),
        ),
        migrations.AddField(
            model_name="distrito",
            name="zon_id",
            field=models.ForeignKey(
                db_column="zon_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="maestros.zona",
            ),
        ),
    ]
