# Generated (manual) to restore migration history expected by later migrations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pago",
            fields=[
                ("PAP_ID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "PAP_FECHA_HORA",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "PAP_VALOR",
                    models.DecimalField(max_digits=12, decimal_places=2),
                ),
            ],
            options={
                "db_table": "PAGO",
            },
        ),
        # Cuota model previously existed here. Removed because the current
        # codebase uses ConceptoContable and related models instead. This
        # placeholder was intentionally left out to avoid referencing a
        # non-existent model in runtime. Historical migrations were kept
        # elsewhere; squash migration should be used for new projects.
        migrations.CreateModel(
            name="ComprobanteDescarga",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ("filename", models.CharField(max_length=255)),
            ],
        ),
    ]
# Generated by Django 5.2.7 on 2025-10-12 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Historical Cuota model removed from migration to prevent references
        # to a model that no longer exists in the codebase. The concept is
        # replaced by ConceptoContable and other payment models.
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('medio', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia Bancaria'), ('TARJETA', 'Tarjeta de Crédito/Débito'), ('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque'), ('WEBPAY', 'WebPay Plus'), ('OTRO', 'Otro')], max_length=40)),
                ('referencia', models.CharField(blank=True, help_text='Número de transferencia, transacción, etc.', max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VERIFICANDO', 'Verificando'), ('PAGADO', 'Pagado'), ('FALLIDO', 'Fallido'), ('ANULADO', 'Anulado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=15)),
                ('fecha_pago', models.DateField(blank=True, help_text='Fecha en que se realizó el pago', null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha límite para el pago', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComprobanteDescarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descargado_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descargas_comprobantes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Descarga de Comprobante',
                'verbose_name_plural': 'Descargas de Comprobantes',
                'db_table': 'payment_receipt_downloads',
            },
        ),
    ]
