# Generated by Django 5.2.7 on 2025-10-12 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    # This migration was generated as part of a multi-step refactor.
    # Ensure it's not treated as 'initial' since we provide a manual 0001_initial.
    initial = False

    dependencies = [
        ("payments", "0001_initial"),
        ("preinscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pago",
            name="preinscripcion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pagos",
                to="preinscriptions.preinscripcion",
            ),
        ),
        migrations.AddField(
            model_name="pago",
            name="registrado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pagos_registrados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # The Cuota model was removed from the current codebase; the
        # historical migration that added a FK from Cuota to Pago is skipped
        # here to avoid referencing a non-existent model.
        migrations.AddField(
            model_name="comprobantedescarga",
            name="pago",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="descargas",
                to="payments.pago",
            ),
        ),
        # AlterUniqueTogether on Cuota removed because Cuota no longer exists.
    ]
