# Generated by Django 5.2.7 on 2025-10-13 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_pago_comprobante"),
        ("preinscriptions", "0001_initial"),
    ]

    operations = [
        # Cuota-related alter/remove operations removed because Cuota was
        # previously removed from the models. These were kept historically
        # but are skipped here to avoid referencing non-existent models.
        migrations.RemoveField(
            model_name="pago",
            name="preinscripcion",
        ),
        migrations.RemoveField(
            model_name="pago",
            name="registrado_por",
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("method", models.CharField(max_length=50)),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "preinscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="preinscriptions.preinscripcion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-date"],
            },
        ),
        migrations.DeleteModel(
            name="ComprobanteDescarga",
        ),
        # Historical deletion of Cuota skipped; model no longer exists.
        migrations.DeleteModel(
            name="Pago",
        ),
    ]
