# Generated by Django 5.2.7 on 2025-10-19 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aplicacion",
            fields=[
                ("apl_id", models.AutoField(primary_key=True, serialize=False)),
                ("apl_descripcion", models.CharField(max_length=50)),
                ("apl_vigente", models.BooleanField()),
            ],
            options={
                "verbose_name": "Aplicación",
                "verbose_name_plural": "Aplicaciones",
                "db_table": "aplicacion",
            },
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                ("pel_id", models.AutoField(primary_key=True, serialize=False)),
                ("pel_descripcion", models.CharField(max_length=50)),
                ("pel_vigente", models.BooleanField()),
            ],
            options={
                "verbose_name": "Perfil",
                "verbose_name_plural": "Perfiles",
                "db_table": "perfil",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("usu_id", models.AutoField(primary_key=True, serialize=False)),
                ("usu_username", models.CharField(max_length=100, unique=True)),
                ("usu_password", models.CharField(max_length=128)),
                ("usu_ruta_foto", models.TextField()),
                ("usu_vigente", models.BooleanField()),
                (
                    "pel_id",
                    models.ForeignKey(
                        db_column="pel_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "usuario",
            },
        ),
        migrations.CreateModel(
            name="PerfilAplicacion",
            fields=[
                ("pea_id", models.AutoField(primary_key=True, serialize=False)),
                ("pea_ingresar", models.BooleanField()),
                ("pea_modificar", models.BooleanField()),
                ("pea_eliminar", models.BooleanField()),
                ("pea_consultar", models.BooleanField()),
                (
                    "apl_id",
                    models.ForeignKey(
                        db_column="apl_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.aplicacion",
                    ),
                ),
                (
                    "pel_id",
                    models.ForeignKey(
                        db_column="pel_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil Aplicación",
                "verbose_name_plural": "Perfiles Aplicaciones",
                "db_table": "perfil_aplicacion",
                "unique_together": {("pel_id", "apl_id")},
            },
        ),
    ]
