# Generated by Django 5.2.8 on 2025-11-15 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("maestros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PagoCambioPersona",
            fields=[
                ("pcp_id", models.AutoField(primary_key=True, serialize=False)),
                ("pcp_fecha_hora", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Cambio en Pago de Persona",
                "verbose_name_plural": "Cambios en Pagos de Personas",
                "db_table": "pago_cambio_persona",
            },
        ),
        migrations.CreateModel(
            name="PagoComprobante",
            fields=[
                ("pco_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Pago asociado a Comprobante",
                "verbose_name_plural": "Pagos asociados a Comprobantes",
                "db_table": "pago_comprobante",
            },
        ),
        migrations.CreateModel(
            name="PagoPersona",
            fields=[
                ("pap_id", models.AutoField(primary_key=True, serialize=False)),
                ("pap_fecha_hora", models.DateTimeField()),
                ("pap_tipo", models.IntegerField()),
                ("pap_valor", models.DecimalField(decimal_places=6, max_digits=21)),
                (
                    "pap_observacion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Pago de Persona",
                "verbose_name_plural": "Pagos de Personas",
                "db_table": "pago_persona",
            },
        ),
        migrations.CreateModel(
            name="Prepago",
            fields=[
                ("ppa_id", models.AutoField(primary_key=True, serialize=False)),
                ("ppa_valor", models.DecimalField(decimal_places=6, max_digits=21)),
                ("ppa_observacion", models.TextField(blank=True, null=True)),
                ("ppa_vigente", models.BooleanField()),
            ],
            options={
                "verbose_name": "Prepago",
                "verbose_name_plural": "Prepagos",
                "db_table": "prepago",
            },
        ),
        migrations.CreateModel(
            name="ComprobantePago",
            fields=[
                ("cpa_id", models.AutoField(primary_key=True, serialize=False)),
                ("cpa_fecha_hora", models.DateTimeField()),
                ("cpa_fecha", models.DateField()),
                ("cpa_numero", models.IntegerField()),
                ("cpa_valor", models.DecimalField(decimal_places=6, max_digits=21)),
                (
                    "coc_id",
                    models.ForeignKey(
                        db_column="coc_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maestros.conceptocontable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comprobante de Pago",
                "verbose_name_plural": "Comprobantes de Pago",
                "db_table": "comprobante_pago",
            },
        ),
    ]
