# Generated by Django 5.2.8 on 2025-11-15 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cursos", "0002_initial"),
        ("pagos", "0001_initial"),
        ("personas", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comprobantepago",
            name="pec_id",
            field=models.ForeignKey(
                db_column="pec_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="personas.personacurso",
            ),
        ),
        migrations.AddField(
            model_name="comprobantepago",
            name="usu_id",
            field=models.ForeignKey(
                db_column="usu_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="usuarios.usuario",
            ),
        ),
        migrations.AddField(
            model_name="pagocambiopersona",
            name="per_id",
            field=models.ForeignKey(
                db_column="per_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="personas.persona",
            ),
        ),
        migrations.AddField(
            model_name="pagocambiopersona",
            name="usu_id",
            field=models.ForeignKey(
                db_column="usu_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="usuarios.usuario",
            ),
        ),
        migrations.AddField(
            model_name="pagocomprobante",
            name="cpa_id",
            field=models.ForeignKey(
                db_column="cpa_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="pagos.comprobantepago",
            ),
        ),
        migrations.AddField(
            model_name="pagopersona",
            name="cur_id",
            field=models.ForeignKey(
                db_column="cur_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="cursos.curso",
            ),
        ),
        migrations.AddField(
            model_name="pagopersona",
            name="per_id",
            field=models.ForeignKey(
                db_column="per_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="personas.persona",
            ),
        ),
        migrations.AddField(
            model_name="pagopersona",
            name="usu_id",
            field=models.ForeignKey(
                db_column="usu_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="usuarios.usuario",
            ),
        ),
        migrations.AddField(
            model_name="pagocomprobante",
            name="pap_id",
            field=models.ForeignKey(
                db_column="pap_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="pagos.pagopersona",
            ),
        ),
        migrations.AddField(
            model_name="pagocambiopersona",
            name="pap_id",
            field=models.ForeignKey(
                db_column="pap_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="pagos.pagopersona",
            ),
        ),
        migrations.AddField(
            model_name="prepago",
            name="cur_id",
            field=models.ForeignKey(
                db_column="cur_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="cursos.curso",
            ),
        ),
        migrations.AddField(
            model_name="prepago",
            name="pap_id",
            field=models.ForeignKey(
                blank=True,
                db_column="pap_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pagos.pagopersona",
            ),
        ),
        migrations.AddField(
            model_name="prepago",
            name="per_id",
            field=models.ForeignKey(
                db_column="per_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="personas.persona",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pagocomprobante",
            unique_together={("pap_id", "cpa_id")},
        ),
    ]
