# Generated by Django 5.2.7 on 2025-12-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pagos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comprobantepago",
            name="cpa_archivo",
            field=models.FileField(blank=True, null=True, upload_to="comprobantes/"),
        ),
        migrations.AddField(
            model_name="comprobantepago",
            name="cpa_tipo",
            field=models.IntegerField(
                choices=[(1, "Ingreso"), (2, "Egreso")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="pagopersona",
            name="pap_tipo",
            field=models.IntegerField(choices=[(1, "Ingreso"), (2, "Egreso")]),
        ),
    ]
