# Generated by Django 5.2.7 on 2025-12-03 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maestros", "0001_initial"),
        ("pagos", "0002_comprobantepago_cpa_archivo_comprobantepago_cpa_tipo_and_more"),
        ("proveedores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pagopersona",
            name="pap_estado",
            field=models.IntegerField(
                choices=[(1, "Pagado"), (2, "Anulado")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="pagopersona",
            name="pap_observacion",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name="PagoProveedor",
            fields=[
                ("ppr_id", models.AutoField(primary_key=True, serialize=False)),
                ("ppr_fecha", models.DateField()),
                ("ppr_valor", models.DecimalField(decimal_places=6, max_digits=21)),
                (
                    "ppr_observacion",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "ppr_archivo",
                    models.FileField(
                        blank=True, null=True, upload_to="comprobantes_proveedores/"
                    ),
                ),
                (
                    "coc_id",
                    models.ForeignKey(
                        db_column="coc_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maestros.conceptocontable",
                    ),
                ),
                (
                    "prv_id",
                    models.ForeignKey(
                        db_column="prv_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proveedores.proveedor",
                    ),
                ),
                (
                    "usu_id",
                    models.ForeignKey(
                        db_column="usu_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago a Proveedor",
                "verbose_name_plural": "Pagos a Proveedores",
                "db_table": "pago_proveedor",
            },
        ),
    ]
