# Generated by Django 5.2.7 on 2025-11-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preinscripcion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="preinscripcion",
            name="vehiculo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="preinscripcion",
            name="vehiculo_marca",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="preinscripcion",
            name="vehiculo_modelo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="preinscripcion",
            name="vehiculo_patente",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
