# Generated by Django 5.1.3 on 2025-12-01 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archivos", "0002_initial"),
        ("preinscripcion", "0002_preinscripcion_vehiculo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="archivo",
            field=models.FileField(
                blank=True, null=True, upload_to="documentos_preinscripcion/"
            ),
        ),
        migrations.AlterField(
            model_name="documento",
            name="archivo_relacionado",
            field=models.ForeignKey(
                blank=True,
                db_column="archivo_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos_asociados",
                to="archivos.archivo",
            ),
        ),
    ]
